function PlotToFileColorPNG(fig, filename, width_cm, height_cm, dpi)
    % Default DPI if not provided
    if nargin < 5
        dpi = 600;  % 推荐：论文插图 600 dpi
    end

    % Set figure size in centimeters
    set(fig, 'Units', 'centimeters');
    set(fig, 'Position', [0, 0, width_cm, height_cm]);

    % Export to PNG
    exportgraphics(fig, filename, ...
        'ContentType', 'image', ...
        'BackgroundColor', 'white', ...
        'Resolution', dpi, ...
        'Width',  width_cm, ...
        'Height', height_cm, ...
        'Padding', 'tight', ...
        'Units', 'centimeters');
end